-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 20:50:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` DEFAULT CHARACTER SET utf8 ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`alunos` (
  `idalunos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `complemento` VARCHAR(25) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `fone` VARCHAR(13) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idalunos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`turmas` (
  `idturmas` INT NOT NULL AUTO_INCREMENT,
  `turma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`materias` (
  `idmaterias` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`grade` (
  `turmas_idturmas` INT NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  PRIMARY KEY (`turmas_idturmas`, `materias_idmaterias`),
  INDEX `fk_turmas_has_materias_materias1_idx` (`materias_idmaterias` ASC),
  INDEX `fk_turmas_has_materias_turmas1_idx` (`turmas_idturmas` ASC),
  CONSTRAINT `fk_turmas_has_materias_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `colegio`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_materias_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `colegio`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`professores` (
  `idprofessores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `complemento` VARCHAR(25) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `fone` VARCHAR(13) NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  PRIMARY KEY (`idprofessores`),
  INDEX `fk_professores_materias1_idx` (`materias_idmaterias` ASC),
  CONSTRAINT `fk_professores_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `colegio`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`matriculas` (
  `idmatriculas` INT NOT NULL AUTO_INCREMENT,
  `turmas_idturmas` INT NOT NULL,
  `alunos_idalunos` INT NOT NULL,
  `mensalidade` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NULL,
  `dtinicio` DATE NOT NULL,
  `dtfim` DATE NOT NULL,
  INDEX `fk_alunos_has_turmas_turmas1_idx` (`turmas_idturmas` ASC),
  INDEX `fk_alunos_has_turmas_alunos1_idx` (`alunos_idalunos` ASC),
  PRIMARY KEY (`idmatriculas`),
  CONSTRAINT `fk_alunos_has_turmas_alunos1`
    FOREIGN KEY (`alunos_idalunos`)
    REFERENCES `colegio`.`alunos` (`idalunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `colegio`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
